const SERVER_ERROR_CODE = 500;
const BAD_REQUEST_CODE = 400;
const NOT_FOUND_CODE = 404;
const RESOURCE_CONFLICT_CODE = 409;
const INVALID_CREDENTIALS_CODE = 401;

module.exports = {
  SERVER_ERROR_CODE,
  BAD_REQUEST_CODE,
  NOT_FOUND_CODE,
  RESOURCE_CONFLICT_CODE,
  INVALID_CREDENTIALS_CODE,
};
